theme: jekyll-theme-architect
title: Javed Imran
description: <i>jimran at cs dot iitr dot ac dot in</i> <br/> [<a style="color:white; text-decoration:underline;"  target="_blank" rel="noopener noreferrer" href = "https://scholar.google.co.in/citations?user=osu7-JoAAAAJ&hl=en&oi=sra">Google Scholar</a>]
