theme: jekyll-theme-cayman
title: Javed Imran
description: <i>jimran@cs.iitr.ac.in</i> <br/>Machine Vision Lab<br/>Department of Computer Science & Engineering <br/> Indian Institute of Technology Roorkee <br/>  [<a style="color:black;"  target="_blank" rel="noopener noreferrer" href = "https://scholar.google.co.in/citations?user=osu7-JoAAAAJ&hl=en&oi=sra">Google Scholar</a>]
