theme: jekyll-theme-cayman
title: Javed Imran
description: <i>jimran at cs dot iitr dot ac dot in</i> <br/>Machine Vision Lab, S-211, South Block <br/>Department of Computer Science & Engineering <br/> Indian Institute of Technology Roorkee <br/>  [<a href = "https://scholar.google.co.in/citations?user=osu7-JoAAAAJ&hl=en&oi=sra">Google Scholar</a>]
