theme: jekyll-theme-cayman
title: Javed Imran
description: <i>jimran@cs.iitr.ac.in</i>, [<a style="color:white;"  target="_blank" rel="noopener noreferrer" href = "https://scholar.google.co.in/citations?user=osu7-JoAAAAJ&hl=en&oi=sra">Google Scholar</a>]
