theme: jekyll-theme-cayman
title: Javed Imran
description: <i>jimran at cs dot iitr dot ac dot in</i> <br/>Machine Vision Lab, S-211, South Block <br/>Department of Computer Science & Engineering <br/> Indian Institute of Technology Roorkee
<br/>
