theme: jekyll-theme-cayman
title: Javed Imran
description: Machine Vision Lab, S-211, South Block, Department of Computer Science & Engineering, Indian Institute of Technology Roorkee, Roorkee 247667, Uttarakhand, India
